accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'


urlpatterns = [
    path('item/list/', views.ItemListView.as_view(), name='item_list'),
    path('item/create/', views.ItemCreateView.as_view(), name='item_create'),
    path('item/detail/<int:pk>', views.ItemDetailView.as_view(), name='item_detail'),
    path('item/update/<int:pk>', views.ItemUpdateView.as_view(), name='item_update'),
    path('item/delete/<int:pk>', views.ItemDeleteView.as_view(), name='item_delete'),
    path('user/item/list/<user_id>', views.UserItemListView.as_view(), name='user_item_list'),
]

company/urls.py
from django.urls import path
from . import views

app_name = 'company'


urlpatterns = [
    # path('company/item/list/', views.CompanyListView.as_view(), name='company_list'),
    # path('company/item/detail/<int:pk>/', views.CompanyDetailView.as_view(), name='company_detail'),
    path('reply/create/<int:pk>/', views.ReplyCreateView.as_view(), name='reply_create'),
    path('company/reply/update/<int:pk>/', views.ReplyUpdateView.as_view(), name='company_update'),
    path('reply/delete/<int:pk>/', views.ReplyDeleteView.as_view(), name='reply_delete'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('allauth/', include('allauth.urls')),
    path('', views.HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('company/', include('company.urls')),
    path('users/', include('users.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'


urlpatterns = [
    path('create/', views.UserCreateView.as_view(), name='users_create'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('update/<int:pk>', views.UserUpdateView.as_view(), name='update'),
]

accounts/models.py
from users.models import User
from django.db import models
from django.utils import timezone
from django.conf import settings


class Item(models.Model):

    CATEGORY_CHOICES = (
        ('shirt', 'シャツ'),
        ('pant', 'パンツ'),
        ('Tshirt', 'Tシャツ'),
    )
    CONDITION_CHOICES = (
        ('s', 'S'),
        ('a', 'A'),
        ('b', 'B'),
        ('c', 'C'),
    )

    name = models.CharField('ブランド', max_length=50)
    item_model = models.CharField('モデル名', max_length=50)
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES)
    condition = models.CharField(max_length=1, choices=CONDITION_CHOICES)
    text = models.TextField('備考')
    created_at = models.DateTimeField(auto_now_add=True)
    contributor = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Image(models.Model):
    src = models.ImageField('添付画像')
    target = models.ForeignKey(
        Item, verbose_name='アイテム',
        blank=True, null=True,
        on_delete=models.CASCADE, related_name='images'
    )





# class Type (models.Model):
#     name = models.CharField('ブランド', max_length=50)
#     item_model = models.CharField('モデル名', max_length=50)
#     category = models.ForeignKey(Item, on_delete=models.CASCADE ,related_name='category')
#     condition = models.ForeignKey(Item, on_delete=models.CASCADE ,related_name='condition')
#     text = models.TextField('備考')

#     def __str__(self):
#         return self.name + ' ' + self.club.name


# class Item_model (models.Model):
#     item_model = models.CharField('モデル名', max_length=50)

#     def __str__(self):
#         return self.name


# class Category (models.Model):
#     name = models.CharField('アイテムタイプ', max_length=50)

#     def __str__(self):
#         return self.name


# class Condition (models.Model):
#     name = models.CharField('状態ランク', max_length=5)

#     def __str__(self):
#         return self.name


# class Comment (models.Model):
#     text = models.TextField('備考')

#     def __str__(self):
#         return self.text
# # Create your models here.

accounts/forms.py
from django import forms
from .models import Item, Image


class ItemCreateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Item
        fields = ('__all__')


ImageFormset = forms.inlineformset_factory(
    Item, Image, fields ='__all__',
    extra=5,
)

accounts/views.py
from django.db.models import query
from django.db.models.query import QuerySet
from company.models import Reply
from users.models import User
from users.views import OnlyYouMixin
from django.http import request
from django.shortcuts import render
from django.contrib import messages
from django.urls import reverse_lazy
from .forms import ItemCreateForm, ImageFormset
from .models import Item, Image
from django.views.generic import CreateView, ListView, UpdateView, DetailView, DeleteView
from django.db.models import Q
from datetime import datetime
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.http import HttpResponseRedirect
from .notify import send_notification




class ItemListView(LoginRequiredMixin, ListView):
    model = Item
    template_name = "accounts/item_list.html"
    context_object_name = 'items'
    paginate_by = 10
    ordering = ['-created_at']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        item_with = []
        context["target"] = item_with
        all_item = Item.objects.all()
        for item in all_item:
            image_list = Image.objects.filter(target_id=item)
            item_image = {
            item,
            image_list
            }
            item_with.append(item_image)
        print(context)
        return context




    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     item_list = []
    #     item = Item.objects.values('id','images')
    #     item_list.append(item)
    #     all_items = Item.objects.all()
    #     for item in all_items:
    #         print(item)
    #         image_list = Image.objects.filter(target_id=item)
    #         context["images"] = item_list
    #         print(context)
    #         return context


    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     item_id = {}
    #     item_list = []
    #     images = 'target_id'
    #     item_id['id'] = images
    #     item_id = Item.objects.values('id')
    #     item_list.append(item_id)
    #     all_item = Item.objects.all()
    #     # print(item_list)→ここでitemList in dictのクエリが一つできる
    #     for item in all_item:
    #         images = {}
    #         images = Image.objects.filter(target_id=item_id).values()
    #         item_list.append(images)
    #         context["images"] = images
    #         print(item_list)
    #     return context

        #     images ={}
        #     image_list = []
        #     images = Image.objects.filter(target_id=item_id)
        #     image_list.append(images)
        #     item_list.append(images)
        #     context["images"] = images
        #     print(item_list)
        # return context
        # ↑リストはまとめられたが、全オブジェクトでまとまってる



        # item_list = Item.objects.values('id')
        # for item_list in Image.objects.select_related('target').filter(target_id__in=item_list)
        # context["images"] = Image.objects.filter(target_id__in=item_list)
        # context["images"] = Image.objects.select_related('target').filter(target_id__in=item_list)
        # return context


    def get_queryset(self):
        current_user = self.request.user
        q_word = self.request.GET.get('query')
        if current_user.is_customer:
            return Item.objects.filter(contributor_id=current_user.id)
        elif q_word:
            object_list = Item.objects.filter(
                Q(name__icontains=q_word) | Q(category__icontains=q_word) | Q(contributor__user_name__icontains=q_word))
            return object_list
        else:
            return Item.objects.all()

    # def get_queryset(self):
    #     q_word = self.request.GET.get('query')

    #     if q_word:
    #         object_list = Item.objects.filter(
    #             Q(name__icontains=q_word) | Q(category__icontains=q_word) | Q(contributor__user_name__icontains=q_word))
    #     else:
    #         object_list = Item.objects.all()
    #     return object_list

class UserItemListView(ListView):
    model = Item
    template_name = "accounts/user_item_list.html"
    context_object_name = 'user_item'
    paginate_by = 10
    ordering = ['-created_at']

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)
    # 表示されねえ・・・forループの書き方？

    # def get_context_data(self, **kwargs):
    #     user = self.request.user
    #     context = super().get_context_data(**kwargs)
    #     context["items"] = user.item_set.all().order_by('-created_at')
    #     return context


class ItemDetailView(LoginRequiredMixin, DetailView):
    model = Item
    template_name = "accounts/item_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["replys"] = Reply.objects.filter(target_id=self.kwargs['pk'])
        return context



class ItemCreateView(LoginRequiredMixin, CreateView):
    model = Item
    form_class = ItemCreateForm
    formset = ImageFormset
    template_name = "accounts/item_create.html"


    def get_context_data(self, **kwargs):
        data = super(ItemCreateView, self).get_context_data(**kwargs)
        if self.request.POST:
            data['formset'] = ImageFormset(self.request.POST, self.request.FILES)
        else:
            data['formset'] = ImageFormset()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        image_formset = context['formset']

        if image_formset.is_valid():
            with transaction.atomic():
                image_formset.instance = self.object
                image_formset.save()
                self.object = form.save()
                send_notification(self.object, '登録')

        return super(ItemCreateView, self).form_valid(image_formset)

    def get_success_url(self):
        return reverse_lazy('accounts:item_list')

class ItemUpdateView(LoginRequiredMixin, UpdateView):
    model = Item
    form_class = ItemCreateForm
    formset = ImageFormset
    template_name = "accounts/item_update.html"

    def get_context_data(self, **kwargs):
        data = super(ItemUpdateView, self).get_context_data(**kwargs)
        if self.request.POST:
            data['formset'] = ImageFormset(self.request.POST, self.request.FILES)
        else:
            data['formset'] = ImageFormset()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        image_formset = context['formset']

        if image_formset.is_valid():
            with transaction.atomic():
                image_formset.instance = self.object
                image_formset.save()
                self.object = form.save()

        return super(ItemUpdateView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('accounts:item_detail',  kwargs={'pk': self.object.pk})

class ItemDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'accounts/item_delete.html'
    model = Item

    success_url = reverse_lazy('accounts:item_list')

    def delete(self, request, *args, **kwargs):
        result = super().delete(request, *args, **kwargs)
        messages.success(
            self.request, '「{}」を削除しました'.format(self.object))
        return result


# def item_list(request):
#     form = ItemCreateForm(request.POST or None)
#     context = {'form': form}
#     if request.method == 'POST' and form.is_valid():
#         post = form.save(commit=False)
#         image_formset = ImageFormset(request.POST, files=request.FILES, instance=post)  # 増えた
#         if  image_formset.is_valid():
#             post.save()
#             image_formset.save()
#             return redirect('accounts:index')

#         # エラーメッセージつきのformsetをテンプレートへ渡すため、contextに格納
#         else:
#             context['image_formset'] = image_formset

#     # GETのとき
#     else:
#         # 空のformsetをテンプレートへ渡す
#         context['image_formset'] = ImageFormset()  # 増えた

#     return render(request, 'accounts/item_list.html', context)

templates/accounts/item_create.html
{% extends 'base.html' %}
{% load static %}
{% block contents %}

<form  method="post" class="create" enctype="multipart/form-data">
    <h2>概算希望商品</h2>
    {{ form.as_p }}
{% for form in formset.forms %}
    <h2>添付画像</h2>
    {{ formset.management_form }}
            {{ form.as_p }}
            <hr>
{% endfor %}
    {% csrf_token %}
    <button type="submit" href="{% url 'accounts:item_list' %}" class="btn btn-primary">送信</button>
</form>

{% endblock %}

templates/accounts/item_delete.html
{% extends 'base.html' %}

{% block contents %}
{% if user.is_authenticated %}
    <h2>Delete</h2>
    <p>本当に{{ item.name }}を削除しますか？<p>
    <form method="POST" >{% csrf_token %}
        <button type="submit" href="{% url 'accounts:item_list' %}" class="save btn btn-danger">delete</button>
    </form>
{% endif %}
{% endblock %}

templates/accounts/item_detail.html
{% extends 'base.html' %}
{% load static %}

{% block contents %}
    <body>
        <p>ユーザー: {{ item.contributor.user_name }}</p>
            <p>アイテム名: {{ item.name }}</p>
            <p>カテゴリー: {{ item.category }}</p>
            <p>状態: {{ item.condition }}</p>
            <p>モデル名: {{ item.item_model }}</p>
            <p>作成日: {{ item.created_at }}</p>
            <p>備考: {{ item.text }}</p>
        {% if user.is_authenticated %}
        <a class="btn btn-default" href="{% url 'accounts:item_update' pk=item.pk %}">編集</a>
        <a class="btn btn-default" href="{% url 'accounts:item_delete' pk=item.pk %}">削除</a>
        <h2>コメント</h2>
        <ul>
        {% for reply in replys %}
        会社:{{ user.company_name }}<br>
        金額:{{ reply.price }}<br>
        備考:{{ reply.text }}<br>
        <a class="btn btn-default" href="{% url 'company:reply_delete' pk=reply.pk %}">削除</a><br>
        {% endfor %}
        </ul>
        {% endif %}
        {% if not user.is_customer.is_superuser %}
        <a class="btn btn-default" href="{% url 'company:reply_create' pk=item.pk %}">新規概算</a>
        {% endif %}


</body>
{% endblock %}

templates/accounts/item_list.html
{% extends 'base.html' %}
{% load static %}

{% block contents %}
    <body>
    <div class="post">
        {% for item in object_list %}
            ユーザー: <a href="{% url 'users:profile' pk=item.contributor.pk %}">{{ items.contributor.user_name }}</a>
            アイテム名: <a href="{% url 'accounts:item_detail' pk=item.pk %}">{{ item.name }}</a>
            <p>カテゴリー: {{ item.category }}</p>
            {% for image in object_list %}
        イメージ：<img src="{{ item.src.url }}" style="width: 300px;height: auto;"/>
        {% endfor %}
        {% endfor %}

        </div>
    </body>
{% endblock %}
<a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a>

templates/accounts/item_update.html
{% extends 'base.html' %}
{% load static %}
{% block contents %}

<form action="" method="post" enctype="multipart/form-data">
    <h2>概算希望商品</h2>
    {{ form.as_p }}
{% for form in formset.forms %}
    <h2>添付画像</h2>
    {{ image_formset.management_form }}
            {{ form.as_p }}
            <hr>
{% endfor %}
    {% csrf_token %}
    <button type="submit" href="{% url 'accounts:item_list' %}" class="btn btn-primary">送信</button>
</form>

{% endblock %}

templates/accounts/user_item_list.html
{% extends 'base.html' %}
{% load static %}

{% block contents %}
    <body>
    <div class="post">

            {% for item in user_item %}
            ユーザー: {{ item.contributor.user_name }}</a>
            アイテム名: <a href="{% url 'accounts:item_detail' pk=item.pk %}">{{ item.name }}</a>
            <p>カテゴリー: {{ item.category }}</p>
            {% endfor %}

        </div>
    </body>
{% endblock %}