mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('allauth/', include('allauth.urls')),
    path('', views.HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('company/', include('company.urls')),
    path('users/', include('users.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'


urlpatterns = [
    path('create/', views.UserCreateView.as_view(), name='users_create'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('update/<int:pk>', views.UserUpdateView.as_view(), name='update'),
]

mysite/views.py
from django.views.generic import TemplateView

class HomeView(TemplateView):
    template_name = "mysite/home.html"

templates/mysite/home.html
{% extends "base.html" %}

{% block title %}{% endblock %}

{% block contents %}
<h2>Amount！</h2>
{% if user.is_authenticated %}
ログインユーザー{{ user.get_username }} さん
<p><a href="{% url 'users:logout' %}">ログアウト</a></p>
{% else %}
<p><a href="{% url 'users:login' %}">ログイン</a></p>
<p><a href="{% url 'users:users_create' %}">新規ユーザー登録</a></p>
{% endif %}
{% endblock %}