accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'


urlpatterns = [
    path('item/list/', views.ItemListView.as_view(), name='item_list'),
    path('item/create/', views.ItemCreateView.as_view(), name='item_create'),
    path('item/detail/<int:pk>', views.ItemDetailView.as_view(), name='item_detail'),
    path('item/update/<int:pk>', views.ItemUpdateView.as_view(), name='item_update'),
    path('item/delete/<int:pk>', views.ItemDeleteView.as_view(), name='item_delete'),
    path('user/item/list/<user_id>', views.UserItemListView.as_view(), name='user_item_list'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('allauth/', include('allauth.urls')),
    path('', views.HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('company/', include('company.urls')),
    path('users/', include('users.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'


urlpatterns = [
    path('create/', views.UserCreateView.as_view(), name='users_create'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('update/<int:pk>', views.UserUpdateView.as_view(), name='update'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    {% comment %} <link rel="stylesheet" href="{% static 'css/accounts.css' %}"> {% endcomment %}
   {% block title %}
   {% endblock title %}
 <!--Navbar Starts Here-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
    <a class="navbar-brand" href="#">トップ</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>

        </ul>
        {% if user.is_authenticated %}


        <ul class="navbar-nav">
            <li class="nav-item active">
            <a class="nav-link"  href="{% url 'accounts:item_create' %}">新規投稿 <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
            <a class="nav-link"  href="{% url 'users:profile' user.pk %}">プロフィール <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{user.username}}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'accounts:item_list' %}">アイテムリスト</a>
                {% if not perms.users.is_customer %}
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'company:company_list' %}">全アイテムリスト</a>
                {% endif %}
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Logout</a>
            </div>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0"  action="{% url 'accounts:item_list'%}" method='GET'>
            <input class="form-control mr-sm-2" type="search" name='query' aria-label="Search" placeholder='Search' value={{request.GET.query}}  >
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        {% else %}

        <a class="btn btn-outline-secondary" href="#">Login</a>
        <a class="btn btn-primary ml-2 mr-2" href="#">Register</a>

        {% endif %}
    </div>
    </nav>
    <!--Navbar Ends-->
  </head>
  <body>
    {% block contents %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends "base.html" %}
 
{% block title %}ホーム{% endblock %}
 
{% block content %}
<h2>ホーム</h2>
{% if user.is_authenticated %}
ようこそ {{ user.get_username }} さん
<p><a href="{% url 'account_logout' %}">ログアウト</a></p>
{% else %}
<p><a href="{% url 'account_login' %}">ログイン</a></p>
{% endif %}
{% endblock %}