accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'


urlpatterns = [
    path('item/list/', views.ItemListView.as_view(), name='item_list'),
    path('item/create/', views.ItemCreateView.as_view(), name='item_create'),
    path('item/detail/<int:pk>', views.ItemDetailView.as_view(), name='item_detail'),
    path('item/update/<int:pk>', views.ItemUpdateView.as_view(), name='item_update'),
    path('item/delete/<int:pk>', views.ItemDeleteView.as_view(), name='item_delete'),
    path('user/item/list/<user_id>', views.UserItemListView.as_view(), name='user_item_list'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('allauth/', include('allauth.urls')),
    path('', views.HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('company/', include('company.urls')),
    path('users/', include('users.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'


urlpatterns = [
    path('create/', views.UserCreateView.as_view(), name='users_create'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('update/<int:pk>', views.UserUpdateView.as_view(), name='update'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import (BaseUserManager, AbstractBaseUser)


class UserManager(BaseUserManager):
    def create_user(self, email, date_of_birth, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            date_of_birth=date_of_birth,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    # def _create_user_(self, email, date_of_birth, password=None):


    def create_superuser(self, email, date_of_birth, password):
        user = self.create_user(
            email,
            password=password,
            date_of_birth=date_of_birth,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    user_name = models.CharField('ユーザーネーム', max_length=100, default='')
    full_name = models.CharField('氏名', max_length=100, blank=False, default='')
    company_name = models.CharField('企業名', max_length=100, blank=True, default='')
    email = models.EmailField(
        verbose_name='email',
        max_length=255,
        unique=True,
    )
    date_of_birth = models.DateField()
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_customer = models.BooleanField(default=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['date_of_birth']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

users/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth.forms import AuthenticationForm
from .models import User


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'user_name', 'full_name', 'company_name', 'date_of_birth')
        widgets = {
            'date_of_birth': forms.SelectDateWidget
        }

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'user_name', 'full_name', 'company_name', 'password', 'date_of_birth')

    def clean_password(self):
        return self.initial["password"]


class LoginForm(AuthenticationForm):
    """ログインフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = (
            'user_name', 'email',
            'full_name', 'company_name',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

users/views.py
from django.shortcuts import render
from django.views.generic import CreateView, DetailView, UpdateView
from .models import User
from accounts.models import Item
from .forms import LoginForm, UserCreationForm, UserUpdateForm
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from .forms import LoginForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

class OnlyYouMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser

class UserCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    template_name = 'users/signup.html'

    def form_valid(self, form):
        result = super().form_valid(form)
        return result

    def get_success_url(self):
        return reverse_lazy('users/profile', kwargs={'pk': self.object.pk})


class ProfileView(LoginRequiredMixin, DetailView):
    model = User
    template_name = "users/profile.html"


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user_item"] = Item.objects.filter(contributor_id=self.kwargs['pk'])
        return context

class UserUpdateView(OnlyYouMixin, UpdateView):
    form_class = UserUpdateForm
    success_url = reverse_lazy('users:profile')
    template_name = 'users/update.html'

    def get_object(self):
        return self.request.user

    def form_valid(self, form):
        result = super().form_valid(form)
        return result

    def get_success_url(self):
        return reverse_lazy('users:profile', kwargs={'pk': self.object.pk})

class Logout(LogoutView):
    template_name = 'mysite/home.html'


class Login(LoginView):
    form_class = LoginForm
    template_name = 'users/login.html'

templates/users/login.html
{% extends "base.html" %}
{% block contents %}
<form action="" method="POST">
    <div class="col-md-6 offset-md-3">
        <div class="card">
            <div class="cardbody">
                {{ form.non_field_errors }}
                {% for field in form %}
                    {{ field }}
                    {{ field.errors }}
                    <hr>
                {% endfor %}
                <button type="submit" class="btn btn-success btn-lg btn-block" ><a href="{% url 'home' %}">ログイン</button>
                <input type="hidden" name="next" value="{{ next }}" />
                <p><a href="{% url 'users:users_create' %}">新規ユーザー登録</a></p>
                {% csrf_token %}
            </div>
        </div>
    </div>
</form>
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block contents %}

        <h2>ユーザー名:{{ user.user_name }}</h2>
        <h2>本名:{{ user.full_name }}</h2>
        <h2>会社名:{{ user.company_name }}</h2>
        <h2>生年月日:{{ user.date_of_birth }}</h2>
        <h2>Eメールアドレス:{{ user.email }}</h2>

        <label>
        <a href="{% url 'users:update' user.pk  %}" class="btn btn-primary ">変更</a>
        </label>
        <h3>アイテムリスト</h3>
        {% for item in user_item %}
        ブランド: <a href="{% url 'accounts:item_detail' pk=item.pk %}">{{ item.name }}</a>
        <p>カテゴリー: {{ item.category }}</p>
        {% endfor %}
{% endblock %}

templates/users/signup.html
{% extends 'base.html' %}
{% load static %}


{% block contents %}

<head>
    <meta charset="utf-8" />
    <title>ユーザー</title>
</head>

<body>
    <h1>新規ユーザー作成画面</h1>
    <form method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="登録">
    </form>
</body>
{% endblock %}

templates/users/update.html
{% extends 'base.html' %}
{% load static %}


{% block contents %}

<head>
    <meta charset="utf-8" />
    <title>ユーザー</title>
</head>

<body>
    <h1>登録情報の編集</h1>
    <form method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <li><input type="submit" href="{% url 'users:profile' user.pk %}" value="登録"></li>
    </form>
</body>
{% endblock %}